[project]
name = "labomatics"
version = "0.4.0"

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version", "cli/pyproject.toml:tool.poetry.version"]
tag_format = "v{version}"
commit_message = "chore(release): v{version} [skip ci]"
major_on_zero = false

[tool.semantic_release.changelog]
exclude_commit_patterns = [
    "^chore\\(release\\):",
    "^Merge (pull request|branch)",
]

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.branches.dev]
match = "dev"
prerelease = true
prerelease_token = "rc"
