FROM python:3.11-slim
WORKDIR /app
RUN pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry install --only main --no-directory
COPY labomatics ./labomatics

CMD ["poetry", "run", "scheduler-worker"]
