"""initial

Revision ID: 2470168507ad
Revises: 
Create Date: 2026-08-01 16:23:20.851030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2470168507ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_keycloak_id', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_actor', 'audit_log', ['actor_keycloak_id', 'created_at'], unique=False)
    op.create_index('idx_audit_log_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_table('cluster',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('default_storage', sa.String(), nullable=False),
    sa.Column('sdn_zone', sa.String(), nullable=False),
    sa.Column('wan_bridge', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default_for_new_cohorts', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_cluster_is_default', 'cluster', ['is_default_for_new_cohorts'], unique=False, postgresql_where=sa.text('is_default_for_new_cohorts = true'))
    op.create_table('cohort',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'year')
    )
    op.create_table('ip_range',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('network', postgresql.CIDR(), nullable=False),
    sa.Column('gateway', postgresql.INET(), nullable=False),
    sa.Column('exclusions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('keycloak_user_id', sa.Uuid(), nullable=True),
    sa.Column('proxmox_userid', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('keycloak_user_id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('proxmox_userid')
    )
    op.create_table('vxlan_range',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vni_min', sa.Integer(), nullable=False),
    sa.Column('vni_max', sa.Integer(), nullable=False),
    sa.Column('base_network', postgresql.CIDR(), nullable=False),
    sa.Column('exclusions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cluster_credential',
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('encrypted_token_secret', postgresql.BYTEA(), nullable=False),
    sa.Column('encryption_key_version', sa.Integer(), nullable=False),
    sa.Column('quota_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_table('cohort_cluster',
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'cluster_id')
    )
    op.create_index('idx_cohort_cluster_cluster_id', 'cohort_cluster', ['cluster_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enrollment_student_date', 'enrollment', ['student_id', 'start_date'], unique=False)
    op.create_index('uq_enrollment_active', 'enrollment', ['student_id'], unique=True, postgresql_where=sa.text('end_date IS NULL'))
    op.create_table('ip_range_cluster',
    sa.Column('ip_range_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ip_range_id'], ['ip_range.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_range_id', 'cluster_id')
    )
    op.create_table('student_cluster_extra',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_cluster_extra_active', 'student_cluster_extra', ['student_id', 'cluster_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('teacher_cohort',
    sa.Column('teacher_keycloak_id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_keycloak_id', 'cohort_id')
    )
    op.create_table('vxlan_range_cluster',
    sa.Column('vxlan_range_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vxlan_range_id'], ['vxlan_range.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vxlan_range_id', 'cluster_id')
    )
    op.create_table('ip_allocation',
    sa.Column('ip_range_cluster_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ip_range_cluster_id'], ['ip_range_cluster.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ip_alloc_address_active', 'ip_allocation', ['ip_range_cluster_id', 'ip_address'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_index('idx_ip_alloc_student_active', 'ip_allocation', ['ip_range_cluster_id', 'student_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_table('vxlan_allocation',
    sa.Column('vxlan_range_cluster_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('vni', sa.Integer(), nullable=False),
    sa.Column('subnet', postgresql.CIDR(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vxlan_range_cluster_id'], ['vxlan_range_cluster.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vxlan_alloc_student_active', 'vxlan_allocation', ['vxlan_range_cluster_id', 'student_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_index('idx_vxlan_alloc_vni_active', 'vxlan_allocation', ['vxlan_range_cluster_id', 'vni'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_table('lab_provisioning',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('access_origin', sa.String(), nullable=False),
    sa.Column('vxlan_allocation_id', sa.Uuid(), nullable=True),
    sa.Column('ip_allocation_id', sa.Uuid(), nullable=True),
    sa.Column('proxmox_pool', sa.String(), nullable=True),
    sa.Column('proxmox_vm_id', sa.Integer(), nullable=True),
    sa.Column('proxmox_vnet', sa.String(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ip_allocation_id'], ['ip_allocation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vxlan_allocation_id'], ['vxlan_allocation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'cluster_id')
    )
    op.create_index('idx_lab_prov_cluster', 'lab_provisioning', ['cluster_id'], unique=False)
    op.create_index('idx_lab_prov_status', 'lab_provisioning', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lab_prov_status', table_name='lab_provisioning')
    op.drop_index('idx_lab_prov_cluster', table_name='lab_provisioning')
    op.drop_table('lab_provisioning')
    op.drop_index('idx_vxlan_alloc_vni_active', table_name='vxlan_allocation', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index('idx_vxlan_alloc_student_active', table_name='vxlan_allocation', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_table('vxlan_allocation')
    op.drop_index('idx_ip_alloc_student_active', table_name='ip_allocation', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index('idx_ip_alloc_address_active', table_name='ip_allocation', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_table('ip_allocation')
    op.drop_table('vxlan_range_cluster')
    op.drop_table('teacher_cohort')
    op.drop_index('idx_student_cluster_extra_active', table_name='student_cluster_extra', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('student_cluster_extra')
    op.drop_table('ip_range_cluster')
    op.drop_index('uq_enrollment_active', table_name='enrollment', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_index('idx_enrollment_student_date', table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index('idx_cohort_cluster_cluster_id', table_name='cohort_cluster')
    op.drop_table('cohort_cluster')
    op.drop_table('cluster_credential')
    op.drop_table('vxlan_range')
    op.drop_table('student')
    op.drop_table('ip_range')
    op.drop_table('cohort')
    op.drop_index('idx_cluster_is_default', table_name='cluster', postgresql_where=sa.text('is_default_for_new_cohorts = true'))
    op.drop_table('cluster')
    op.drop_index('idx_audit_log_resource', table_name='audit_log')
    op.drop_index('idx_audit_log_actor', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
