"""proxmox user

Revision ID: a972cf0a0dcb
Revises: e996c779cc81
Create Date: 2026-09-03 15:21:39.455532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a972cf0a0dcb'
down_revision: Union[str, Sequence[str], None] = 'e996c779cc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_credential', sa.Column('user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_credential', 'user')
    # ### end Alembic commands ###
