"""proxmox user

Revision ID: a972cf0a0dcb
Revises: e996c779cc81
Create Date: 2026-09-03 15:21:39.455532

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a972cf0a0dcb"
down_revision: str | Sequence[str] | None = "e996c779cc81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster_credential", sa.Column("user", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster_credential", "user")
    # ### end Alembic commands ###
