"""lab_owner_and_default_cluster

Revision ID: e996c779cc81
Revises: 2470168507ae
Create Date: 2026-09-03 14:22:53.534279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e996c779cc81'
down_revision: Union[str, Sequence[str], None] = '2470168507ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Ajouter d'abord les colonnes comme nullable pour le backfill
    op.add_column('ip_allocation', sa.Column('owner_keycloak_id', sa.UUID(), nullable=True))
    op.add_column('ip_allocation', sa.Column('owner_role', sa.String(), nullable=True))
    op.add_column('lab_provisioning', sa.Column('owner_keycloak_id', sa.UUID(), nullable=True))
    op.add_column('lab_provisioning', sa.Column('owner_role', sa.String(), nullable=True))
    op.add_column('vxlan_allocation', sa.Column('owner_keycloak_id', sa.UUID(), nullable=True))
    op.add_column('vxlan_allocation', sa.Column('owner_role', sa.String(), nullable=True))

    # Backfill : copier student_id→owner_keycloak_id depuis student.keycloak_user_id
    op.execute("""
    UPDATE ip_allocation SET
        owner_keycloak_id = COALESCE(student.keycloak_user_id, ip_allocation.owner_keycloak_id),
        owner_role = 'student'
    FROM student
    WHERE ip_allocation.student_id = student.id
    """)

    op.execute("""
    UPDATE lab_provisioning SET
        owner_keycloak_id = COALESCE(student.keycloak_user_id, lab_provisioning.owner_keycloak_id),
        owner_role = 'student'
    FROM student
    WHERE lab_provisioning.student_id = student.id
    """)

    op.execute("""
    UPDATE vxlan_allocation SET
        owner_keycloak_id = COALESCE(student.keycloak_user_id, vxlan_allocation.owner_keycloak_id),
        owner_role = 'student'
    FROM student
    WHERE vxlan_allocation.student_id = student.id
    """)

    # Rendre NOT NULL maintenant que les valeurs existent
    op.alter_column('ip_allocation', 'owner_keycloak_id', nullable=False)
    op.alter_column('ip_allocation', 'owner_role', nullable=False)
    op.alter_column('lab_provisioning', 'owner_keycloak_id', nullable=False)
    op.alter_column('lab_provisioning', 'owner_role', nullable=False)
    op.alter_column('vxlan_allocation', 'owner_keycloak_id', nullable=False)
    op.alter_column('vxlan_allocation', 'owner_role', nullable=False)

    op.create_table('lab_vm',
    sa.Column('lab_provisioning_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=False),
    sa.Column('disk', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_provisioning_id'], ['lab_provisioning.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lab_vm_cluster', 'lab_vm', ['cluster_name'], unique=False)
    op.create_index('idx_lab_vm_provisioning', 'lab_vm', ['lab_provisioning_id'], unique=False)
    op.create_index('idx_lab_vm_state', 'lab_vm', ['state'], unique=False)

    # Ajouter la colonne user à cluster_credential (nullable pour parsing Proxmox token)
    op.add_column('cluster_credential', sa.Column('user', sa.String(), nullable=True))

    op.add_column('cohort_cluster', sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index('idx_cohort_cluster_is_default', 'cohort_cluster', ['is_default'], unique=False, postgresql_where=sa.text('is_default = true'))

    # Mettre à jour les indices et contraintes maintenant que backfill est fait
    op.alter_column('ip_allocation', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_ip_alloc_student_active'), table_name='ip_allocation', postgresql_where='(released_at IS NULL)')
    op.create_index('idx_ip_alloc_owner_active', 'ip_allocation', ['owner_keycloak_id', 'ip_address'], unique=True, postgresql_where=sa.text('released_at IS NULL'))

    op.alter_column('lab_provisioning', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_lab_prov_owner_cluster', 'lab_provisioning', ['owner_keycloak_id', 'cluster_id'])

    op.alter_column('vxlan_allocation', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_vxlan_alloc_student_active'), table_name='vxlan_allocation', postgresql_where='(released_at IS NULL)')
    op.create_index('idx_vxlan_alloc_owner_active', 'vxlan_allocation', ['owner_keycloak_id', 'vni'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_credential', 'user')
    op.drop_index('idx_vxlan_alloc_owner_active', table_name='vxlan_allocation', postgresql_where=sa.text('released_at IS NULL'))
    op.create_index(op.f('idx_vxlan_alloc_student_active'), 'vxlan_allocation', ['vxlan_range_cluster_id', 'student_id'], unique=True, postgresql_where='(released_at IS NULL)')
    op.alter_column('vxlan_allocation', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('vxlan_allocation', 'owner_role')
    op.drop_column('vxlan_allocation', 'owner_keycloak_id')
    op.drop_constraint('uq_lab_prov_owner_cluster', 'lab_provisioning', type_='unique')
    op.alter_column('lab_provisioning', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('lab_provisioning', 'owner_role')
    op.drop_column('lab_provisioning', 'owner_keycloak_id')
    op.drop_index('idx_ip_alloc_owner_active', table_name='ip_allocation', postgresql_where=sa.text('released_at IS NULL'))
    op.create_index(op.f('idx_ip_alloc_student_active'), 'ip_allocation', ['ip_range_cluster_id', 'student_id'], unique=True, postgresql_where='(released_at IS NULL)')
    op.alter_column('ip_allocation', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ip_allocation', 'owner_role')
    op.drop_column('ip_allocation', 'owner_keycloak_id')
    op.drop_index('idx_cohort_cluster_is_default', table_name='cohort_cluster', postgresql_where=sa.text('is_default = true'))
    op.drop_column('cohort_cluster', 'is_default')
    op.drop_index('idx_lab_vm_state', table_name='lab_vm')
    op.drop_index('idx_lab_vm_provisioning', table_name='lab_vm')
    op.drop_index('idx_lab_vm_cluster', table_name='lab_vm')
    op.drop_table('lab_vm')
    # ### end Alembic commands ###
