name: Prod CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  release:
    needs: lint
    uses: ./.github/workflows/release.yaml
    with:
      github_ref: ${{ github.ref }}
    secrets: inherit

  docker:
    if: needs.release.outputs.released == 'true'
    needs: release
    uses: ./.github/workflows/docker.yaml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit

  pypi:
    if: needs.release.outputs.released == 'true'
    needs: release
    uses: ./.github/workflows/pypi.yaml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
